# Using the official MySQL image
FROM mysql:8.0

# Setting root password
ENV MYSQL_ROOT_PASSWORD=PayMyBuddy07.

# Setting the database name
ENV MYSQL_DATABASE=patientinfoservice

# Copy the SQL scripts to the /docker-entrypoint-initdb.d/ directory
COPY create_table.sql /docker-entrypoint-initdb.d/
